//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALERIA
    {
        public long ID { get; set; }
        public string NOMBRE { get; set; }
        public string VARIEDAD { get; set; }
        public string PAIS { get; set; }
        public Nullable<int> OURSCORE { get; set; }
        public string FARM { get; set; }
        public string IMAGEN { get; set; }
    }
}
